/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculate.h"

int *add_1_svc(operands *argp, struct svc_req *rqstp) {
	static int  result;

	printf("Adding %d to %d...\n", argp->a, argp->b);
	result = argp->a + argp->b;
	printf("Done! Result = %d\n\n", result);

	return &result;
}

int *sub_1_svc(operands *argp, struct svc_req *rqstp) {
	static int  result;

	printf("Removing %d from %d...\n", argp->a, argp->b);
	result = argp->a - argp->b;
	printf("Done! Result = %d\n\n", result);

	return &result;
}

int *multiply_1_svc(operands *argp, struct svc_req *rqstp) {
	static int  result;

	printf("Multiplying %d for %d...\n", argp->a, argp->b);
	result = argp->a * argp->b;
	printf("Done! Result = %d\n\n", result);

	return &result;
}

int *divide_1_svc(operands *argp, struct svc_req *rqstp){
	static int  result;

	printf("Dividing %d by %d...\n", argp->a, argp->b);

	if (argp->b != 0) {
		result = argp->a / argp->b;
		printf("Done! Result = %d\n\n", result);
	} else {
		fprintf(stderr, "Can't divide by 0!\n\n");
		result = -1;
	}

	return &result;
}
