/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATE_H_RPCGEN
#define _CALCULATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	int a;
	int b;
	int operator;
};
typedef struct operands operands;

#define PROG 1111111
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(operands *, CLIENT *);
extern  int * add_1_svc(operands *, struct svc_req *);
#define SUB 2
extern  int * sub_1(operands *, CLIENT *);
extern  int * sub_1_svc(operands *, struct svc_req *);
#define MULTIPLY 3
extern  int * multiply_1(operands *, CLIENT *);
extern  int * multiply_1_svc(operands *, struct svc_req *);
#define DIVIDE 4
extern  int * divide_1(operands *, CLIENT *);
extern  int * divide_1_svc(operands *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define SUB 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define MULTIPLY 3
extern  int * multiply_1();
extern  int * multiply_1_svc();
#define DIVIDE 4
extern  int * divide_1();
extern  int * divide_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATE_H_RPCGEN */
